### ISSUE TITLE
Integrate build123d & Netgen

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#297]
The Netgen/NGSolve system, available at https://ngsolve.org/, enables CFD analysis of BREP parts and can generate objects using the OpenCascade CAD core. It appears possible to convert build123d objects into native Netgen objects for analysis, potentially unlocking a diverse range of applications. Netgen incorporates a basic version of build123d's Algebra system, suggesting a potential avenue for collaboration between these projects.

**Comment by rmsc** [comment]
I'm very interested in getting this working:

```python
with bd.BuildPart() as cylinder:
    bd.Cylinder(10, 10)

assert cylinder.part is not None
occ_shape = cylinder.part.wrapped

print(type(occ_shape))
# <class 'OCP.OCP.TopoDS.TopoDS_Compound'>

netgen_shape = From_PyOCC(occ_shape)
geo = OCCGeometry(netgen_shape)
```

Not working unfortunately:

```bash
AttributeError: 'OCP.OCP.TopoDS.TopoDS_Compound' object has no attribute 'this'
```

**Comment by gumyr** [comment]
Netgen and build123d use different versions of OpenCascade - https://pypi.org/project/netgen-occt/ and https://pypi.org/project/cadquery-ocp/ respectively. However, build123d can export to brep format and netgen can import brep so that might be a good way to bridge the two worlds.

**Comment by zalo** [comment]
~~I wasn't even able to get b123d and ngsolve imported in the same script due to conflicting OCC named types in pybind11…~~ **Update:** On Python 3.12, `cadquery-ocp` ships OCCT 7.8.1 matching `netgen-occt` 7.8.1, so both import fine in the same process — no subprocess needed! (On Python 3.9, `cadquery-ocp` is stuck at 7.7.2 which causes the pybind11 clash.)

Neither BREP nor STEP preserves face-level names, so boundary conditions still need to be passed separately via geometric matching + `ngmesh.SetBCName()`.

Here's the simplified single-process solution (requires Python 3.12+):

<img width="1200" height="900" alt="Image" src="https://github.com/user-attachments/assets/74d19555-890c-472b-b0ca-601349d61181" />

```py
"""build123d -> ngsolve: Poisson solve with automatic face name propagation.

On Python 3.12+, cadquery-ocp and netgen-occt both use OCCT 7.8.1, so they
coexist in one process. Direct shape passing still doesn't work (different
pybind11 wrappers), so BREP file interchange is needed. Face names don't
survive BREP/STEP export — use geometric matching + ngmesh.SetBCName().

See: https://github.com/gumyr/build123d/issues/297
"""

import math
import tempfile

import build123d as bd
from netgen.occ import OCCGeometry
import ngsolve as ngs

# 1. Build geometry in build123d
part = bd.Cylinder(10, 20) - bd.Cylinder(5, 20)

# 2. Transfer via BREP (direct shape passing not supported)
with tempfile.NamedTemporaryFile(suffix=".brep") as tmp:
    bd.export_brep(part, tmp.name)
    geo = OCCGeometry(tmp.name)

# 3. Propagate face names by matching geometric centers
b123d_faces = [
    (f.center().X, f.center().Y, f.center().Z,
     "ends" if abs(f.center().Z) > 1 else "walls")
    for f in part.faces()
]

ngmesh = geo.GenerateMesh(maxh=2)

for ng_idx, ng_face in enumerate(geo.shape.faces):
    nc = ng_face.center
    best_label = min(
        b123d_faces,
        key=lambda fm: math.sqrt(
            (nc.x - fm[0]) ** 2 + (nc.y - fm[1]) ** 2 + (nc.z - fm[2]) ** 2
        ),
    )[3]
    ngmesh.SetBCName(ng_idx, best_label)

mesh = ngs.Mesh(ngmesh)
print(f"Boundaries:  {mesh.GetBoundaries()}")

# 4. Solve Poisson: -Laplacian(u) = 1, u=0 on ends
fes = ngs.H1(mesh, order=2, dirichlet="ends")
u, v = fes.TnT()
a = ngs.BilinearForm(ngs.grad(u) * ngs.grad(v) * ngs.dx).Assemble()
f = ngs.LinearForm(1 * v * ngs.dx).Assemble()
gfu = ngs.GridFunction(fes)
gfu.vec.data = a.mat.Inverse(fes.FreeDofs()) * f.vec
print(f"DOFs:        {fes.ndof} ({sum(fes.FreeDofs())} free)")
print(f"Solution:    {min(gfu.vec):.4f} .. {max(gfu.vec):.4f}")
```

**Comment by rmsc** [comment]
I got both to work in the same script, no issues there:

```python
import build123d as bd
from netgen.occ import OCCGeometry
import tempfile

with bd.BuildPart() as cylinder:
    bd.Cylinder(10, 10)

netgen_shape = None
with tempfile.NamedTemporaryFile(suffix=".brep") as tmp:
    assert cylinder.part is not None
    bd.export_brep(cylinder.part, file_path=tmp.name)
    netgen_shape = OCCGeometry(tmp.name)
``` 

The labels not going across is actually a problem, the netgen API for locating features isn't very friendly..

**Comment by rmsc** [comment]
From what I gathered, there's no way to persist labels using BREP, but it is possible using STEP. And from what I understood, netgen does pick up these STEP labels.

**Comment by zalo** [comment]
Some follow-up after more testing:

**Re: both imports working in the same script** — We confirmed this **does work on Python 3.12** where `cadquery-ocp==7.8.1.1.post1` and `netgen-occt==7.8.1` both use the same OCCT version. On Python 3.9, `cadquery-ocp` is stuck at 7.7.2 which clashes with `netgen-occt` 7.8.1 (pybind11 `generic_type: type "gp_Pnt" is already registered!`). So **the fix is simply using Python 3.12+** where the OCCT versions match. (We also needed `LD_LIBRARY_PATH` set to the conda env's lib dir due to a libexpat resolution issue, but that's environment-specific.)

**Direct shape passing** still doesn't work even with matched OCCT versions — `OCP.TopoDS_Compound` and `netgen.TopoDS_Shape` are different pybind11 wrapper types. BREP file interchange remains necessary.

**Re: STEP preserving face labels** — We tested this extensively and found that neither BREP nor STEP preserves face-level names:

- build123d's `face.label` is ephemeral — `part.faces()` returns new wrapper objects each call
- build123d's XCAF exporter writes labels for Shape-tree nodes (Solid/Compound) but not individual Faces
- We manually wrote face-level XCAF labels via `shape_tool.AddSubShape()` + `TDataStd_Name.Set_s()` — the STEP writer did not include them
- On the netgen side, `face.name` set on BREP-imported geometry doesn't propagate to mesh boundaries

**Working solution**: `ngmesh.SetBCName(idx, label)` after meshing, with face matching by geometric center distance. On Python 3.12 this all works in a single process — no subprocess needed. See updated code in the comment above.

**Comment by gumyr** [comment]
There was a significant rework of the step exporter done recently (only available in the `dev` branch) that should keep labels (and colors).  However, labels (and colors) can only be applied at the Shape level and not Faces within a Solid.

**Comment by rmsc** [comment]
I just realized it's actually fairly easy to move the labels over:

```python
import build123d as bd
from netgen.occ import OCCGeometry
import tempfile

with bd.BuildPart() as cylinder:
    bd.Cylinder(10, 10)

netgen_shape = None
with tempfile.NamedTemporaryFile(suffix=".brep") as tmp:
    assert cylinder.part is not None
    bd.export_brep(cylinder.part, file_path=tmp.name)
    netgen_shape = OCCGeometry(tmp.name).shape

# HERE:
faces = cylinder.faces().sort_by(bd.Axis.Z)
bottom = faces.first.location_at()
top = faces.last.location_at()
netgen_shape.faces.Nearest(Pnt(bottom.X, bottom.Y, bottom.Z)).name = "bottom"
netgen_shape.faces.Nearest(Pnt(top.X, top.Y, top.Z)).name = "top"
```

A simple utility function makes it a lot more readable:

```python
def name_netgen_face(ng_shape, bd_face, name):
    center = bd_face.location_at()
    ng_shape.faces.Nearest(Pnt(center.X, center.Y, center.Z)).name = name

faces = cylinder.faces().sort_by(bd.Axis.Z)
name_netgen_face(netgen_shape, faces.first, "bottom")
name_netgen_face(netgen_shape, faces.last, "top")
```

So maybe an example is all we need in terms of integration.

**Comment by rmsc** [comment]
As @zalo pointed out, `center()` doesn't work for non-planar surfaces. It turns out `location_at()` returns a point on the surface, which is what we really want.

Just updated the example above, replacing `center()` with `location_at()`.

**Comment by zalo** [comment]
`location_at()` has the same problem — it evaluates at `(u=0.5, v=0.5)` in UV parameter space, which can land outside the trimmed boundary on non-convex faces. Two minimal reproductions:

```python
import build123d as bd
from OCP.BRepClass import BRepClass_FaceClassifier
from OCP.gp import gp_Pnt
import OCP.TopAbs as ta

def on_face(face, pt):
    cl = BRepClass_FaceClassifier(face.wrapped, gp_Pnt(pt.X, pt.Y, pt.Z), 1e-6)
    return cl.State() in (ta.TopAbs_ON, ta.TopAbs_IN)

# Case 1: C-shaped ring (annular sector endcaps)
c_shape = (bd.Cylinder(10, 2) - bd.Cylinder(8, 2)
         - bd.Box(12, 4, 4, align=(bd.Align.MIN, bd.Align.CENTER, bd.Align.CENTER)))

# Case 2: U-channel (L-shaped side walls)
u_channel = bd.Box(20, 10, 2) + bd.Pos(-7.5, 0, 5) * bd.Box(5, 10, 10) + bd.Pos(7.5, 0, 5) * bd.Box(5, 10, 10)

for name, shape in [("C-shape", c_shape), ("U-channel", u_channel)]:
    for i, f in enumerate(shape.faces()):
        loc_pt = f.location_at().position
        if not on_face(f, loc_pt):
            c = f.center()
            print(f"{name} face {i}: location_at OFF face at ({loc_pt.X:.1f}, {loc_pt.Y:.1f}, {loc_pt.Z:.1f}), "
                  f"center also OFF at ({c.X:.1f}, {c.Y:.1f}, {c.Z:.1f})")
```

Output:
```
C-shape face 1: location_at OFF face at (-0.1, 0.0, 1.0), center also OFF at (-0.7, 0.0, 1.0)
C-shape face 3: location_at OFF face at (-0.1, 0.0, -1.0), center also OFF at (-0.7, 0.0, -1.0)
U-channel face 7: location_at OFF face at (-0.0, 5.0, 4.5), center also OFF at (0.0, 5.0, 3.8)
U-channel face 9: location_at OFF face at (0.0, -5.0, 4.5), center also OFF at (0.0, -5.0, 3.8)
```

When these off-face points are passed to `Nearest()`, they can match the wrong netgen face. In the PR we handle this with rejection sampling in UV space — try `center()` first, fall back to random UV samples checked with `BRepClass_FaceClassifier` until one lands inside the trimmed boundary.

**Comment by gumyr** [comment]
I haven't released this yet but here is a Face method that will give you a u,v value within a face:
```py
def find_interior_uv(
    self, max_tries: int = 200, normalize: bool = True
) -> tuple[float, float]:
    """find_interior_uv

    Return a u,v coordinate that lies within - neither outside
    nor on the edge of - self

    Args:
        max_tries (int, optional): maximum # of attempts. Defaults to 200.
        normalize (bool, optional): return uv values in range 0.0-1.0. Defaults to True.

    Raises:
        RuntimeError: Not found

    Returns:
        tuple[float, float]: interior u,v coordinate
    """
    umin, umax, vmin, vmax = self._uv_bounds()
    classifier = BRepClass_FaceClassifier()

    for _ in range(max_tries):
        u = random.uniform(umin, umax)
        v = random.uniform(vmin, vmax)

        # Classify the UV point
        classifier.Perform(self.wrapped, gp_Pnt2d(u, v), 1e-9)

        if classifier.State() == TopAbs_IN:
            if normalize:
                u = (u - umin) / (umax - umin)
                v = (v - vmin) / (vmax - vmin)
            return (u, v)

    raise RuntimeError("Could not find interior (u,v) for face.")
```

**Comment by zalo** [comment]
@gumyr Would you like me to add this function in my PR?
Just had some good netgen usage today and was reminded that it would be nice to have a golden-path in b123d.
https://discord.com/channels/964330484911972403/1074840524181217452/1506839977097695243
